npm:
  build: ./
  command: run dev
  expose:
    - 1234
    - 1337
  ports:
    - "1234:1234"
    - "1337:1337"
  volumes:
    - ~/.npm:/root/.npm
    - ./:/app
  environment:
    VIRTUAL_HOST: hugo.test
    VIRTUAL_PORT: 1234